# =============================================================================
#  C O P Y R I G H T
# -----------------------------------------------------------------------------
#  Copyright (c) 2025-2026 by ETAS GmbH. All rights reserved.
#
#  The reproduction, distribution and utilization of this file as
#  well as the communication of its contents to others without express
#  authorization is prohibited. Offenders will be held liable for the
#  payment of damages. All rights reserved in the event of the grant
#  of a patent, utility model or design.
# =============================================================================

filegroup(
    name = "key_management_test_vectors",
    srcs = [
        "aes256_cmac.key",
        "hmac_sha256.key",
    ],
    visibility = ["//:__subpackages__"],
)
