// =============================================================================
//  C O P Y R I G H T
// -----------------------------------------------------------------------------
//  Copyright (c) 2026 by ETAS GmbH. All rights reserved.
//
//  The reproduction, distribution and utilization of this file as
//  well as the communication of its contents to others without express
//  authorization is prohibited. Offenders will be held liable for the
//  payment of damages. All rights reserved in the event of the grant
//  of a patent, utility model or design.
// =============================================================================

#ifndef SCORE_MW_CRYPTO_API_CERTIFICATE_I_OCSP_REQUEST_EXPORT_HPP
#define SCORE_MW_CRYPTO_API_CERTIFICATE_I_OCSP_REQUEST_EXPORT_HPP

#include "score/result/result.h"
#include "score/span.hpp"

#include <cstddef>
#include <cstdint>
#include <memory>
#include <string_view>

namespace score
{
namespace mw
{
namespace crypto
{

/// @brief Export interface for an OCSP request.
///
/// Provides access to the DER-encoded OCSP request data and the
/// OCSP responder URL. Generated by ICertificateManagementContext::GetOcspRequestData().
class IOcspRequestExport
{
  public:
    using Uptr = std::unique_ptr<IOcspRequestExport>;

    virtual ~IOcspRequestExport() = default;

    IOcspRequestExport(const IOcspRequestExport&) = delete;
    IOcspRequestExport& operator=(const IOcspRequestExport&) = delete;
    IOcspRequestExport(IOcspRequestExport&&) = default;
    IOcspRequestExport& operator=(IOcspRequestExport&&) = default;

    /// @brief Exports the DER-encoded OCSP request into the provided buffer.
    /// @param output Buffer to receive the encoded OCSP request
    /// @return Number of bytes written on success
    virtual score::Result<std::size_t> GetEncodedRequest(score::cpp::span<uint8_t> output) const = 0;

    /// @brief Returns the OCSP responder URL.
    /// @return URL string or empty string_view if not configured
    virtual std::string_view GetResponderUrl() const noexcept = 0;

  protected:
    IOcspRequestExport() = default;
};

}  // namespace crypto
}  // namespace mw
}  // namespace score

#endif  // SCORE_MW_CRYPTO_API_CERTIFICATE_I_OCSP_REQUEST_EXPORT_HPP
