# =============================================================================
#  C O P Y R I G H T
# -----------------------------------------------------------------------------
#  Copyright (c) 2026 by ETAS GmbH. All rights reserved.
#
#  The reproduction, distribution and utilization of this file as
#  well as the communication of its contents to others without express
#  authorization is prohibited. Offenders will be held liable for the
#  payment of damages. All rights reserved in the event of the grant
#  of a patent, utility model or design.
# =============================================================================

# =============================================================================
# FUTURE: Config headers below are not yet in scope. To activate, move the
#         .hpp back to //score/mw/crypto/api/config/ and add to context_configs.
# =============================================================================

load("@rules_cc//cc:defs.bzl", "cc_library")

# cc_library(
#     name = "future_context_configs",
#     hdrs = [
#         "aead_context_config.hpp",
#         "certificate_context_config.hpp",
#         "certificate_verification_context_config.hpp",
#         "cipher_context_config.hpp",
#         "csr_generation_context_config.hpp",
#         "random_context_config.hpp",
#         "sign_context_config.hpp",
#         "verify_signature_context_config.hpp",
#     ],
#     deps = [
#         "//score/mw/crypto/api/common:crypto_common",
#     ],
# )
